models/bike_model.py
from configurations.database import db


class Bike(db.Model):

    __tablename__ = "bikes"

    id = db.Column(db.Integer, primary_key=True)
    modelo = db.Column(db.String(200), nullable=False)
    categoria = db.Column(db.String, nullable=False)
    preco = db.Column(db.String(50), nullable=False)
    status = db.Column(db.String(50), nullable=False, default="disponivel")



    def __repr__(self):
        return f"Bike(modelo='{self.modelo}', categoria='{self.categoria}', preco={self.preco}, disponivel={self.disponivel})"


    def indisponibilizar(self):
        self.disponivel = False

models/task_model.py
from configurations.database import db

class Task(db.Model):
    __tablename__ = 'tasks'

    id = db.Column(db.Integer, primary_key=True)
    conteudo = db.Column(db.String(200), nullable=False)
    completa = db.Column(db.Boolean, default=False)
    prioridade = db.Column(db.String(50), nullable=False, default="Média")
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)

    def __repr__(self):  # Representação textual da tarefa
        return f"Tarefa('{self.conteudo}', '{self.completa}', '{self.prioridade}')"

    def __str__(self):  # Representação textual da tarefa
        return f"Conteúdo: {self.conteudo}, Completa: {self.completa}, Prioridade: {self.prioridade}"

    def completar(self):
        self.completa = True  # Método para marcar a tarefa como completa

models/user_model.py
from werkzeug.security import generate_password_hash, check_password_hash
from configurations.database import db


class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password_hash = db.Column(db.String(255), nullable=False)
    is_admin = db.Column(db.Boolean, default=False)
    active = db.Column(db.Boolean, default=True)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f"<User {self.username}>"

app.py
from flask import Flask, redirect, url_for
from configurations.database import db
from controllers.bike_controller import bike_blueprint
from dotenv import load_dotenv
from urllib.parse import quote
import os

app = Flask(__name__)
app.register_blueprint(bike_blueprint)

# Carrega as variáveis de ambiente do arquivo .env
load_dotenv()

user = os.getenv('DB_USER')
password = os.getenv('DB_PASSWORD')
db_name = os.getenv('DB_NAME')
host = os.getenv('DB_HOST')
port = os.getenv('DB_PORT')

# Converte a senha para bytes antes de usar quote
password = quote(password.encode('utf-8'))

app.config['SQLALCHEMY_DATABASE_URI'] = f"postgresql://{user}:{password}@{host}:{port}/{db_name}"
app.config['SQLALCHEMY_TRACK_NOTIFICATIONS'] = False
app.config['SQLALCHEMY_ECHO'] = True

# Corrigido para db.init_app(app) em vez de db,init_app(app)
db.init_app(app)

if __name__ == '__main__':
    with app.app_context():
        db.create_all()
    app.run(debug=True)

controllers/bike_controller.py
from flask import Blueprint, render_template, request, url_for, redirect
from services.bike_service import BikeService

bike_blueprint: Blueprint = Blueprint('bike', __name__)
bike_service = BikeService()

# Route for listing all bikes
@bike_blueprint.route("/")
def index():
    bicicletas = bike_service.listar_bicicleta()
    return render_template("index.html", bicicletas=bicicletas)

# Route for adding a new bike
@bike_blueprint.route("/adicionarBicicleta", methods=["POST"])
def adicionar_bicicleta():
    modelo = request.form.get("modelo")
    categoria = request.form.get("categoria")
    preco = request.form.get("preco")
    status = request.form.get("status")  # Mantenha assim

    try:
        bike_service.incluir_bicicleta(modelo, categoria, preco, status)  # Mantenha assim
    except ValueError as e:
        return str(e), 400

    return redirect(url_for("bike.index"))

# Route for marking a bike as unavailable (e.g., sold)
@bike_blueprint.route("/indisponibilizarBicicleta/<int:bicicleta_id>")
def indisponibilizar(bicicleta_id):
    try:
        bike_service.vender_bicicleta(bicicleta_id)
    except ValueError as e:
        return str(e), 400
    return redirect(url_for("bike.index"))

@bike_blueprint.route("/removerBicicleta/<int:bicicleta_id>")
def remover(bicicleta_id):
    try:
        bike_service.remover_bicicleta(bicicleta_id)
    except ValueError as e:
        return str(e), 400
    return redirect(url_for("bike.index"))

controllers/task_controller.py
from flask import Blueprint, render_template, request, url_for, redirect, session
from services.task_service import TaskService

task_blueprint = Blueprint('task', __name__, url_prefix="/task")
task_service = TaskService()


@task_blueprint.route("/listar")
def listar():
    # Renderiza o template task_list.html com a lista de tarefas
    if 'user_id' not in session:
        return redirect(url_for('user.login'))

    user_id = session['user_id']
    tarefas = task_service.listar_tarefas(user_id)
    return render_template("task_list.html", tarefas=tarefas)


@task_blueprint.route("/adicionar", methods=["POST"])
def adicionar():
    if 'user_id' not in session:
        return redirect(url_for('user.login'))

    user_id = session['user_id']
    conteudo = request.form.get("tarefa")
    prioridade = request.form.get("prioridade", "Média")

    if prioridade == '':
        prioridade = 'Média'

    try:
        task_service.adicionar_tarefa(conteudo, user_id, prioridade)
    except ValueError as e:
        return str(e), 400

    return redirect(url_for("task.listar"))


@task_blueprint.route("/completar/<int:tarefa_id>")
def completar(tarefa_id):
    try:
        # Marca a tarefa como completa
        task_service.completar_tarefa(tarefa_id)
    except Exception as e:
        return str(e), 400

    return redirect(url_for("task.listar"))


@task_blueprint.route("/remover/<int:tarefa_id>")
def remover(tarefa_id):
    # Remove a tarefa da lista
    try:
        # Marca a tarefa como completa
        task_service.remover_tarefa(tarefa_id)
    except Exception as e:
        return str(e), 400

    return redirect(url_for("task.listar"))

controllers/user_controller.py
from flask import Blueprint, render_template, request, url_for, redirect, flash, session
from models.user_model import User
from repositories.user_repository import UserRepository
from services.user_service import UserService

user_blueprint = Blueprint('user', __name__, url_prefix='/user')


@user_blueprint.route("/adicionar", methods=['GET', 'POST'])
def adicionar_usuario():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        user_exists = User.query.filter_by(username=username).first()
        if user_exists:
            flash('Usuário já existe!', 'danger')
            return redirect(url_for('user.adicionar_usuario'))

        UserRepository.create_user(username, password)
        flash('Usuário cadastrado com sucesso!', 'sucess')
        return redirect(url_for('user.adicionar_usuario'))

    flash ('Bem vindo ao cadastro de usuários!', 'sucess')
    return render_template('add_user.html')


@user_blueprint.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        user = UserService.check_user(username=username, password=password)
        if user:
            user_id, is_admin = user
            session['user_id'] = user_id
            session['is_admin'] = is_admin
            flash('Login realizado com sucesso!', 'success')
            return redirect(url_for('task.listar'))

        flash('Usuário ou senha inválidos!', 'danger')
    return render_template('login.html')


@user_blueprint.route("/logout")
def logout():
    session.pop('user_id', None)
    session.pop('is_admin', None)
    flash('Logout realizado com sucesso!', 'success')
    return redirect(url_for('user.login'))


@user_blueprint.route("/list")
def list_users():
    if 'user_id' not in session or not session.get('is_admin'):
        flash('Acesso negado. Apenas administradores logados podem acessar essa página', 'danger')
        return redirect(url_for('user.login'))

    users = UserService.list_users()
    print(users)
    return render_template('user_list.html', users=users)

templates/add_user.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de usuários</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <h1>Criar Novo Usuário</h1>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <p>{{ category }}</p>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <form action="{{ url_for('user.adicionar_usuario') }}" method="post">
         <label for="username">Nome do usuário:</label>
            <input id="text" id="username" name="username" required>
            <label for="password">Senha:</label>
            <input type="password" id="password" name="password" required>

             <button type="submit">Criar</button>
</body>

</html>

templates/form_user.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de usuários</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <h1>Criar Novo Usuário</h1>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <p>{{ category }}</p>
            {% endfor %}
        {% endif %}
    {% endwith %}
</body>
</html>

templates/index.html
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inventário de Bicicletas</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
<h1>Inventário de Bicicletas</h1>

<!-- Formulário de Adicionar Bicicleta -->
<form action="{{ url_for('bike.adicionar_bicicleta') }}" method="post">
    <input type="text" name="modelo" placeholder="Modelo" required>
    <input type="text" name="categoria" placeholder="Categoria" required>
    <input type="number" step="0.01" name="preco" placeholder="Preço" required>
    <select name="status" required>  <!-- Corrigido para 'status' -->
        <option value="disponivel">Disponível</option>
        <option value="indisponivel">Indisponível</option>
    </select>
    <button type="submit">Adicionar Bicicleta</button>
</form>

<!-- Lista de Bicicletas -->
<ul>
    {% for bicicleta in bicicletas %}
    <li>
        {% if bicicleta.status == 'indisponivel' %}  <!-- Corrigido para 'status' -->
            <del>{{ loop.index }} - Modelo: {{ bicicleta.modelo }} | Categoria: {{ bicicleta.categoria }} | Preço: R$ {{ bicicleta.preco }}</del>
        {% else %}
            {{ loop.index }} - Modelo: {{ bicicleta.modelo }} | Categoria: {{ bicicleta.categoria }} | Preço: R$ {{ bicicleta.preco }}
        {% endif %} <!-- Fechando o if corretamente -->

        <a class="remover" href="{{ url_for('bike.remover', bicicleta_id=bicicleta.id) }}">[Remover]</a>
        {% if bicicleta.status == 'disponivel' %}  <!-- Corrigido para 'status' -->
            <a class="indisponibilizar" href="{{ url_for('bike.indisponibilizar', bicicleta_id=bicicleta.id) }}">[Indisponibilizar]</a>
        {% endif %} <!-- Fechando o if corretamente -->
    </li>
    {% endfor %} <!-- Fechando o for corretamente -->
</ul>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Login</title>
    <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet">
</head>
<body>
    <h1>Login</h1>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul class="flashes">
                {% for category, message in messages %}
                    <li class="{{ category }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

<form action="{{ url_for('user.login') }}" method="post">
    <label for="username">Nome do usuário:</label>
    <input id="username" name="username" required type="text">
    <label for="password">Senha:</label>
    <input id="password" name="password" required type="password">

    <button type="submit">Login</button>
</form>
</body>
</html>

templates/task_list.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tarefas</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <h1>Lista de Tarefas</h1>
    <a href="{{ url_for('user.logout') }}" class="button">Logout</a>    
    <!-- Formulário para adicionar uma nova tarefa -->
    <form action="{{ url_for('task.adicionar') }}" method="post">
        <input type="text" name="tarefa" placeholder="Nova tarefa." required>
        <select name="prioridade" id="prioridade">
           <option value="Alta">Alta</option> 
           <option value="Média" selected>Média</option> 
           <option value="Baixa">Baixa</option> 
        </select>
        <button type="submit">Adicionar</button>
    </form>

    <!-- Exibe a lista de tarefas -->
    <ul>
        {% for tarefa in tarefas %}
        <li>
            {% if tarefa.completa %}
                <del>{{ loop.index }} - {{ tarefa.conteudo }}</del>
            {% else %}
                {{ loop.index }} - {{ tarefa.conteudo }} - {{ tarefa.prioridade }}
            {% endif %}
            
            <!-- Botão para marcar a tarefa como completa -->
            {% if tarefa.completa %}
                <a class="remover" href="{{ url_for('task.remover', tarefa_id=tarefa.id) }}">[Remover]</a>
            {% else %}
                <a href="{{ url_for('task.completar', tarefa_id=tarefa.id) }}">[Completar]</a>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
</body>
</html>

templates/user_list.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tarefas</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <h1>Lista de Usuários</h1>
    <a href="{{ url_for('user.logout') }}" class="button">Logout</a>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <ul class="flashes">
        {% for category, message in messages %}
        <li class="{{ category }}">{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Username</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.username }}</td>
                    <td>{{ 'Ativo' if user.active else 'Desativado' }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>